"""Facial landmark extraction interfaces."""


def detect_landmarks(face_image: dict) -> dict:
    """Detect facial landmarks from a normalized face crop.

    Parameters
    ----------
    face_image:
        Cropped facial image generated by the face detection stage.

    Returns
    -------
    dict
        Placeholder landmark list and model metadata.
    """
    return {
        "landmarks": [],
        "model": "placeholder",
        "face_image": face_image,
    }


def export_landmarks(landmarks: list[tuple[float, float]]) -> dict:
    """Prepare landmark coordinates for downstream geometric transformations.

    Parameters
    ----------
    landmarks:
        Collection of landmark coordinates.

    Returns
    -------
    dict
        Placeholder exported landmark structure.
    """
    return {
        "count": len(landmarks),
        "coordinates": landmarks,
    }
